export const MapActionTypes = {
  SET_LONGITUDE: 'SET_LONGITUDE',
  SET_LATITUDE: 'SET_LATITUDE',
  SET_RIGHT_ASCENSION: 'SET_RIGHT_ASCENSION',
  SET_DECLINATION: 'SET_DECLINATION',
  SET_ZOOM: 'SET_ZOOM',
  SET_STARS_VIEW: 'SET_STARS_VIEW',
  SET_PLANETS_VIEW: 'SET_PLANETS_VIEW',
  SET_SATELLITES_VIEW: 'SET_SATELLITES_VIEW',
  SET_MOON_SUN_VIEW: 'SET_MOON_SUN_VIEW'
};
